# Numpy Basic Operations

In [3]:
import numpy as np

## Artithemetics

Arithmetic operators on arrays apply elementwise.

In [27]:
a = np.arange(5)
b = np.ones(5, dtype=int)

print(f"a =    {a}", f"b =    {b}", sep="\n")
print(f"a+b  = {a+b}")
print(f"a-b  = {a-b}")
print(f"a^2  = {a**2}")
print(f"a*10 = {a*10}")
print(f"a>2  = {a>2}")

a =    [0 1 2 3 4]
b =    [1 1 1 1 1]
a+b  = [1 2 3 4 5]
a-b  = [-1  0  1  2  3]
a^2  = [ 0  1  4  9 16]
a*10 = [ 0 10 20 30 40]
a>2  = [False False False  True  True]


## Product

Unlike in many matrix languages, product operator `*` operates elementwise in numpy, the **dot product** or **matrix product** can be performed by the `@` operator or `dot()` method.

In [40]:
print(f"a =   {a}", f"b =   {b}", sep="\n")
print(f"a*b = {a*b}")
print(f"a@b = {a@b}")
print(f"a.dot(b) = {a.dot(b)}")

a =   [0 1 2 3 4]
b =   [1 1 1 1 1]
a*b = [0 1 2 3 4]
a@b = 10
a.dot(b) = 10


In [54]:
c = np.array([[1, 2], [3, 4]])
d = np.random.default_rng(42).integers(1, 10, (2, 2))

print("c:", c, "d:", d, sep="\n")
print()
print(f"c*d=\n{c*d}")
print()
print(f"c@d=\n{c@d}")

c:
[[1 2]
 [3 4]]
d:
[[1 7]
 [6 4]]

c*d=
[[ 1 14]
 [18 16]]

c@d=
[[13 15]
 [27 37]]


## Upcasting

**Upcasting** will automatically convert the different types to the precise one.

In [12]:
e = np.ones(3, dtype=np.int32)
f = np.linspace(0, np.pi, 3)

print(e)
print(f)
print(e+f)

[1 1 1]
[0.         1.57079633 3.14159265]
[1.         2.57079633 4.14159265]


## Functions

By specifying the axis parameter you can apply an operation along the specified axis of an array:

- **None**: all elemnts in the array or matrix
- **0**: each columns
- **1**: each rows

In [26]:
m = np.random.default_rng(42).random((2, 4))
print(m)
print()
print("m.sum(): ", m.sum())
print("m.sum(axis=0): ", m.sum(axis=0))
print("m.sum(axis=1): ", m.sum(axis=1))
print()
print("m.min()", m.min())
print("m.min(axis=0)", m.min(axis=0))
print("m.min(axis=1)", m.min(axis=1))
print()
print("m.max()", m.max())
print("m.max(axis=0)", m.max(axis=0))
print("m.max(axis=1)", m.max(axis=1))

[[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]]

m.sum():  5.385804144070475
m.sum(axis=0):  [0.8681334  1.41450079 1.61973762 1.48343233]
m.sum(axis=1):  [2.76880044 2.61700371]

m.min() 0.09417734788764953
m.min(axis=0) [0.09417735 0.43887844 0.7611397  0.69736803]
m.min(axis=1) [0.43887844 0.09417735]

m.max() 0.9756223516367559
m.max(axis=0) [0.77395605 0.97562235 0.85859792 0.78606431]
m.max(axis=1) [0.85859792 0.97562235]


### Universal Functions

NumPy provides familiar mathematical functions such as **sin**, **cos**, and **exp** (These are called **universal functions**). They all operate elementwise on an array.

> exp, sqrt, all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [46]:
A = np.arange(4)
print(f"A = {A}")
print(f"np.sqrt(A) = {np.sqrt(A)}")
print(f"np.exp(A) = {np.exp(A)}")
print(f"np.mean(A) = {np.mean(A)}")
print(f"np.median(A) = {np.median(A)}")
print(f"np.all(A) = {np.all(A)}")
print(f"np.any(A) = {np.any(A)}")

A = [0 1 2 3]
np.sqrt(A) = [0.         1.         1.41421356 1.73205081]
np.exp(A) = [ 1.          2.71828183  7.3890561  20.08553692]
np.mean(A) = 1.5
np.median(A) = 1.5
np.all(A) = False
np.any(A) = True
