# Numpy Basic Operations

In [2]:
import numpy as np

## Sort

In [23]:
a = np.arange(5)
a = np.sort(a)  # not an in-place sorting
# [0, 1, 2, 3, 4]

a[::-1].sort()  # perform in-place sorting
# [4, 3, 2, 1, 0]

In [38]:
a = np.random.default_rng(42).integers(0, 10, (2,3,4))
a

array([[[0, 7, 6, 4],
        [4, 8, 0, 6],
        [2, 0, 5, 9]],

       [[7, 7, 7, 7],
        [5, 1, 8, 4],
        [5, 3, 1, 9]]], dtype=int64)

In [40]:
np.sort(a, axis=-1)  # default: sort on last (axis=2 in this case) dimension

array([[[0, 4, 6, 7],
        [0, 4, 6, 8],
        [0, 2, 5, 9]],

       [[7, 7, 7, 7],
        [1, 4, 5, 8],
        [1, 3, 5, 9]]], dtype=int64)

In [45]:
np.sort(a, axis=1)  # sort on the second demension

array([[[0, 0, 0, 4],
        [2, 7, 5, 6],
        [4, 8, 6, 9]],

       [[5, 1, 1, 4],
        [5, 3, 7, 7],
        [7, 7, 8, 9]]], dtype=int64)

In [47]:
np.sort(a, axis=None)[::-1]  # sort on all elements and flatten

array([9, 9, 8, 8, 7, 7, 7, 7, 7, 6, 6, 5, 5, 5, 4, 4, 4, 3, 2, 1, 1, 0,
       0, 0], dtype=int64)

Note: The `axis` uses in `np.sort()` is not as in `max()`, `mean()` and other functions.

- `axis=None` will sort the arrays into **flattened** arrays.
- `axis=n` will sort the arrays on the `n-th` dimension.
    - e.g., `np.sort((3, 3, 1), axis=2)` will sort the elements on the last dimension. 

## Concatenate

In [9]:
a = np.array([[2, 1]])
b = np.arange(4).reshape(2, 2)
a, b

(array([[2, 1]]),
 array([[0, 1],
        [2, 3]]))

In [13]:
print(  np.concatenate((a, b), axis=None)  )
print(  np.concatenate((a, b), axis=0)     )  # default axis
print(  np.concatenate((a.T, b), axis=1)   )

[2 1 0 1 2 3]
[[2 1]
 [0 1]
 [2 3]]
[[2 0 1]
 [1 2 3]]


In [48]:
a = np.arange(9).reshape(3, 3, 1)
b = np.arange(18).reshape(3, 3, 2)
print(a)
print(b)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [50]:
print(  np.concatenate((a, b), axis=None)  )
print(  np.concatenate((a, b), axis=2)     )

[ 0  1  2  3  4  5  6  7  8  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17]
[[[ 0  0  1]
  [ 1  2  3]
  [ 2  4  5]]

 [[ 3  6  7]
  [ 4  8  9]
  [ 5 10 11]]

 [[ 6 12 13]
  [ 7 14 15]
  [ 8 16 17]]]


Note: The `axis` uses in `np.concatenate()` is not as in `max()`, `mean()` and other functions.

- `axis=None` will merge the arrays into **flattened** arrays.
- `axis=n` will merge the arrays on the `n-th` dimension.
    - e.g., `np.concatenate((3, 3, 1), (3, 3, 2), axis=2) = (3, 3, 3)`

## Artithemetics

Arithmetic operators on arrays apply elementwise.

In [27]:
a = np.arange(5)
b = np.ones(5, dtype=int)

print(f"a =    {a}", f"b =    {b}", sep="\n")
print(f"a+b  = {a+b}")
print(f"a-b  = {a-b}")
print(f"a^2  = {a**2}")
print(f"a*10 = {a*10}")
print(f"a>2  = {a>2}")

a =    [0 1 2 3 4]
b =    [1 1 1 1 1]
a+b  = [1 2 3 4 5]
a-b  = [-1  0  1  2  3]
a^2  = [ 0  1  4  9 16]
a*10 = [ 0 10 20 30 40]
a>2  = [False False False  True  True]


## Product

Unlike in many matrix languages, product operator `*` operates elementwise in numpy, the **dot product** or **matrix product** can be performed by the `@` operator or `dot()` method.

In [40]:
print(f"a =   {a}", f"b =   {b}", sep="\n")
print(f"a*b = {a*b}")
print(f"a@b = {a@b}")
print(f"a.dot(b) = {a.dot(b)}")

a =   [0 1 2 3 4]
b =   [1 1 1 1 1]
a*b = [0 1 2 3 4]
a@b = 10
a.dot(b) = 10


In [54]:
c = np.array([[1, 2], [3, 4]])
d = np.random.default_rng(42).integers(1, 10, (2, 2))

print("c:", c, "d:", d, sep="\n")
print()
print(f"c*d=\n{c*d}")
print()
print(f"c@d=\n{c@d}")

c:
[[1 2]
 [3 4]]
d:
[[1 7]
 [6 4]]

c*d=
[[ 1 14]
 [18 16]]

c@d=
[[13 15]
 [27 37]]


## Upcasting

**Upcasting** will automatically convert the different types to the precise one.

In [12]:
e = np.ones(3, dtype=np.int32)
f = np.linspace(0, np.pi, 3)

print(e)
print(f)
print(e+f)

[1 1 1]
[0.         1.57079633 3.14159265]
[1.         2.57079633 4.14159265]


## Functions

By specifying the axis parameter you can apply an operation along the specified axis of an array:

- **None**: all elemnts in the array or matrix
- **0**: each columns
- **1**: each rows

In [26]:
m = np.random.default_rng(42).random((2, 4))
print(m)
print()
print("m.sum(): ", m.sum())
print("m.sum(axis=0): ", m.sum(axis=0))
print("m.sum(axis=1): ", m.sum(axis=1))
print()
print("m.min()", m.min())
print("m.min(axis=0)", m.min(axis=0))
print("m.min(axis=1)", m.min(axis=1))
print()
print("m.max()", m.max())
print("m.max(axis=0)", m.max(axis=0))
print("m.max(axis=1)", m.max(axis=1))

[[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]]

m.sum():  5.385804144070475
m.sum(axis=0):  [0.8681334  1.41450079 1.61973762 1.48343233]
m.sum(axis=1):  [2.76880044 2.61700371]

m.min() 0.09417734788764953
m.min(axis=0) [0.09417735 0.43887844 0.7611397  0.69736803]
m.min(axis=1) [0.43887844 0.09417735]

m.max() 0.9756223516367559
m.max(axis=0) [0.77395605 0.97562235 0.85859792 0.78606431]
m.max(axis=1) [0.85859792 0.97562235]


### Universal Functions

NumPy provides familiar mathematical functions such as **sin**, **cos**, and **exp** (These are called **universal functions**). They all operate elementwise on an array.

> exp, sqrt, all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [46]:
A = np.arange(4)
print(f"A = {A}")
print(f"np.sqrt(A) = {np.sqrt(A)}")
print(f"np.exp(A) = {np.exp(A)}")
print(f"np.mean(A) = {np.mean(A)}")
print(f"np.median(A) = {np.median(A)}")
print(f"np.all(A) = {np.all(A)}")
print(f"np.any(A) = {np.any(A)}")

A = [0 1 2 3]
np.sqrt(A) = [0.         1.         1.41421356 1.73205081]
np.exp(A) = [ 1.          2.71828183  7.3890561  20.08553692]
np.mean(A) = 1.5
np.median(A) = 1.5
np.all(A) = False
np.any(A) = True


# Reference

- https://numpy.org/doc/stable/user/quickstart.html#basic-operations
- https://numpy.org/doc/stable/user/absolute_beginners.html#adding-removing-and-sorting-elements
- https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations
- https://numpy.org/doc/stable/user/absolute_beginners.html#more-useful-array-operations