# Broadcasting

The simplest broadcasting example occurs when an **array** and a **scalar** value are combined in an operation.

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
a * 3

array([3, 6, 9])

## General Broadcasting Rules

When operating on two arrays, numpy will compare two arrays from the last dimension. If the dimensions of two arrays **are equal** or **one of them is 1**, then the `broadcasting` will be performed. Otherwise, a `ValueError` will occur.

For example, we can update the image's RGB values (red, green, blue) separately by multiplying the image by a one-dimensional array with 3 values.

``` python
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3
```

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other, the axes with length 1 are expanded to the size of the larger one. 

``` python
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```



In [43]:
a=np.arange(15).reshape(3, 5)
b=np.arange(5).reshape(1, 5)

print("a:", a)
print()
print("b:", b)
print()
print(a+b)
print((a+b).shape)
print()
print((a*b))
print((a*b).shape)

a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

b: [[0 1 2 3 4]]

[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]
(3, 5)

[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]]
(3, 5)


## Outer Operation

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

In [44]:
a = np.arange(4)[:, np.newaxis]
print(a.shape)
print(a)

(4, 1)
[[0]
 [1]
 [2]
 [3]]


In [45]:
b = np.arange(3)
print(b.shape)
print(b)

(3,)
[0 1 2]


In [46]:
print((a + b).shape)
print(a + b)

(4, 3)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


# Reference

- https://numpy.org/doc/stable/user/quickstart.html#broadcasting-rules
- https://numpy.org/doc/stable/user/basics.broadcasting.html