# Create a Numpy array

* Create an array or matrix from a list
* Create an array or matrix filled with 0's
* Create an array or matrix filled with 1's
* Create an array or matrix with speed
* Create an array with range
* Create an array with linear space
* Create an array or matrix with random generator
    * random.random.default_rng()
    * array of samples from N(3, 6.25)
    * array or matrix of random integers [2, 10)



In [2]:
import numpy as np

## Create an array or matrix from a list

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [43]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

## Create an array or matrix filled with 0's

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Create an array or matrix filled with 1's

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Create an array or matrix with speed

The function `empty` creates an array whose initial content is random and depends on the **state of the memory**. 

The reason to use `empty` over `zeros` (or something similar) is **speed** - just make sure to fill every element afterwards!

In [27]:
np.empty((5, 2))

array([[1.12176055e-311, 1.77863633e-322],
       [0.00000000e+000, 0.00000000e+000],
       [8.48798316e-313, 8.24777728e-071],
       [1.77289997e+160, 5.33241712e-091],
       [2.05998359e+184, 3.67145801e+228]])

## Create an array with range

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(2, 10, 3)  # start, end, step

array([2, 5, 8])

## Create an array with linear space

In [35]:
np.linspace(5, 50, 20)  # start, end, num of elements

array([ 5.        ,  7.36842105,  9.73684211, 12.10526316, 14.47368421,
       16.84210526, 19.21052632, 21.57894737, 23.94736842, 26.31578947,
       28.68421053, 31.05263158, 33.42105263, 35.78947368, 38.15789474,
       40.52631579, 42.89473684, 45.26315789, 47.63157895, 50.        ])

## Create an array or matrix with random generator

### random.random.default_rng()

https://numpy.org/doc/stable/reference/random/generator.html

In [69]:
rng = np.random.default_rng(seed=42)
rng.random((2, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431]])

### array of samples from N(3, 6.25)

In [83]:
# 
rng.normal(3, 2.5, size=(2, 4))             # same
3 + 2.5 * rng.standard_normal(size=(2, 4))  # same

array([[ 4.69728391,  3.16894767,  3.7227985 ,  4.57822056],
       [-0.64288955,  2.20082196,  1.82406836,  1.40280538]])

### array or matrix of random integers from [2, 10)

In [89]:
rng.integers(low=2, high=10, size=(10, 2))

array([[3, 6],
       [6, 8],
       [9, 7],
       [5, 5],
       [5, 8],
       [4, 3],
       [4, 2],
       [2, 2],
       [8, 7],
       [7, 5]], dtype=int64)