# Indexing, Slicing

In [16]:
import numpy as np
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x[1, 3] == x[1][3]  # both are 8

True

Note that `x[1,3]` equals to `x[1][3]` though the second case is **more inefficient** as a new temporary array is created after the first index that is subsequently indexed by 3.

In [18]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [19]:
y[1:5:2, ::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

Above, we use `1:5:2` to control the indexing of the first dimension, we select from row **1** to **5** $[1, 5)$ with step **2**, which are rows 1 and 3.

On rows 1 and 3, we use `::3` to select from **first element to last element** with step **3**, which are the elements with `0, 3, 6` indexes.


## Indexing Arrays or Multidimensional Arrays

In [20]:
x = np.arange(10, 2, -1)
print(x)

[10  9  8  7  6  5  4  3]


In [21]:
print(  x[np.array([0, 1, 2, -1, -2])]   )
print(  x[np.array([[0, 0], [-1, -2]])]  )

[10  9  8  3  4]
[[10 10]
 [ 3  4]]


We can extract the numpy array from an index array, and we can even specify the shape of the result array.

In [22]:
y = np.arange(16).reshape(4, 4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
# select multiple rows by indexing
print(  y[np.array([1, 2, 3])]                   )
print(  y[np.array([1, 2, 3]), 1:4:2]            )

# select specific elements by indexing
print(  y[np.array([1, 2]), np.array([-1, -1])]  ) # same 
print(  y[np.array([1, 2]), -1]                  ) # same

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  7]
 [ 9 11]
 [13 15]]
[ 7 11]
[ 7 11]


## Masking Arrays or Multidimensional Arrays

In [24]:
x = np.arange(10)
print(  x                    )
print(  x[x>5]               )
print(  x[(x>5) & (x<8)]     )
print(  x[(x%2==0) | (x>7)]  )

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[6 7]
[0 2 4 6 8 9]


In [25]:
y = np.arange(30).reshape(6, 5)
print(  y             )
print(  y[y>5]        )
print(  y[y>5].shape  )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
(24,)


In [26]:
print(  y[[True]*3 + [False] + [True] + [False]]        )  # row 0, 1, 2, 4
print(  y[[True]*3 + [False] + [True] + [False], 2::2]  )  # row 0, 1, 2, 4, select 2:end and step=2 each row

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 21 22 23 24]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [22 24]]


## Ellipsis syntax (...)

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then 

- `x[1,2,...]` is equivalent to `x[1,2,:,:,:]`
- `x[...,3]` to `x[:,:,:,:,3]`
- `x[4,...,5,:]` to `x[4,:,:,5,:]`

In [27]:
x = np.arange(50).reshape(5, 2, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [28]:
x[-1, ..., 3]  # same as x[-1, :, 3]

array([43, 48])

In [29]:
x[:3, ...]  # same as x[0:3, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [30]:
x[::2, ..., np.array([0, 2])]  # same as x[0:5:2, :, np.array([0, 2])]

array([[[ 0,  2],
        [ 5,  7]],

       [[20, 22],
        [25, 27]],

       [[40, 42],
        [45, 47]]])

# Reference

- https://numpy.org/doc/stable/user/basics.indexing.html
- https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing
- https://numpy.org/doc/stable/user/quickstart.html#indexing-slicing-and-iterating
- https://numpy.org/doc/stable/user/quickstart.html#advanced-indexing-and-index-tricks