# Shape Manipulation

In [2]:
import numpy as np

## Shape checking

Before we learn how to control the shapes of arrays, we need to know how to find the shape of arrays. There are three properties from a numpy array that can be used to find the shape, dimension, and the total number of elements.

- `ndim` will tell you the number of dimensions of the array
- `size` will tell you the total number of elements of the array
- `shape` will tell you the complete shape of the array from a tuple of integers



In [15]:
A = np.array([[[1, 2, 3], [4, 5, 6]], [[4, 6, 8], [2, 1, 6]]])
A

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 6, 8],
        [2, 1, 6]]])

In [18]:
print(A.shape)
print(A.size)
print(A.ndim)

(2, 2, 3)
12
3


## Reshape

We can use `reshape` to change the shape of arrays without changing the data, but the array you want to produce needs to have the **same number of elements** as the original array. E.g.

- (6) -> (2, 3) -> (1, 2, 3)
- (2, 2, 2, 2) -> (4, 2, 2) -> (4, 4) -> (16)

In [32]:
A = np.arange(6)
print(A.shape)
print(A, "\n")

A = A.reshape(2, 3)
print(A.shape)
print(A, "\n")

A = A.reshape(1, 3, 1, 2)
print(A.shape)
print(A, "\n")

(6,)
[0 1 2 3 4 5] 

(2, 3)
[[0 1 2]
 [3 4 5]] 

(1, 3, 1, 2)
[[[[0 1]]

  [[2 3]]

  [[4 5]]]] 



## Expand Dimension

There are two ways to expand (or insert) a new dimension into our original arrays.

- You can use `np.newaxis` to add a new axis, and the `np.newaxis` is identical to `None`, but with a more specific meaning
- You can expand an array by inserting a new axis at a specified position with `np.expand_dims()`

In [59]:
A = np.arange(5)
print(A.shape)

print(A[..., None].shape)
print(A[..., np.newaxis].shape)
print(A[:, np.newaxis, np.newaxis].shape)
A[:, np.newaxis, np.newaxis]

(5,)
(5, 1)
(5, 1)
(5, 1, 1)


array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [60]:
A = np.arange(5)

print(np.expand_dims(A, axis=0).shape)
print(np.expand_dims(A, axis=1).shape)

(1, 5)
(5, 1)


## Flatten

- `array.ravel()`
- `array.flatten()` 
- `array.reshape(-1)` 

> Reference: [What is the difference between flatten and ravel functions in numpy?](https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy)

In [81]:
A = np.arange(6).reshape(1, 2, 1, 3,)
print(A)

print(A.ravel())
print(A.flatten())
print(A.reshape(-1))

[[[[0 1 2]]

  [[3 4 5]]]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


## “Automatic” Reshaping

When we reshape our arrays, we can omit 1 of the dimensions by assign -1 to it, then numpy will reshape the arrays with a proper dimension automatically.

In [95]:
A = np.arange(30)
A = A.reshape(2, -1, 5)  # -1 means "whatever is needed"

print(A)
print(A.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)


# Reference

- https://numpy.org/doc/stable/user/absolute_beginners.html#how-do-you-know-the-shape-and-size-of-an-array
- https://numpy.org/doc/stable/user/absolute_beginners.html#can-you-reshape-an-array
- https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-convert-a-1d-array-into-a-2d-array-how-to-add-a-new-axis-to-an-array
- https://numpy.org/doc/stable/user/absolute_beginners.html#transposing-and-reshaping-a-matrix
- https://numpy.org/doc/stable/user/quickstart.html#shape-manipulation
- https://numpy.org/doc/stable/user/quickstart.html#automatic-reshaping